commit 15.07.2024 17:10

diff --git a/.github/workflows/filter_test.yaml b/.github/workflows/filter_test.yaml
--- a/.github/workflows/filter_test.yaml
+++ b/.github/workflows/filter_test.yaml
@@ -102,9 +102,10 @@ jobs:
       - name: Generate .env file
         run: |
           echo "BUCKET_NAME=${{ env.BUCKET_NAME }}" > .env
-          echo "ALB_URL=${{ env.ALB_URL }}" >> .env
+          echo "ALB_URL=https:://${{ env.ALB_URL }}" >> .env
           echo "REGION=${{ matrix.region }}" >> .env
           echo "DYNAMODB_TABLE_NAME=${{ env.DYNAMODB_TABLE_NAME }}" >> .env
+          
           # Replace https:// with http:// and append :80
           YOLO_QUEUE_URL_HTTP=$(echo "${{ env.YOLO_QUEUE_URL }}" | sed 's#^https://#http://#')
           echo "YOLO_QUEUE_NAME=${YOLO_QUEUE_URL_HTTP}:80" >> .env
@@ -114,3 +115,20 @@ jobs:
           echo "FILTERS_QUEUE_NAME=${FILTERS_QUEUE_URL_HTTP}:80" >> .env
 
           cat .env
+
+      - name: Create SSH key file + Copy ENV file to EC2 instances
+        run: |
+          FILTERS_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/filters:0.0.${{ github.run_number }}
+          echo "${{ secrets.PRIVATE_KEY }}" >> ssh_key.pem
+          sudo chmod 400 ssh_key.pem
+          # Split IP addresses into an array
+          IFS=' ' read -r -a IPS <<< "$EC2_FILTERS_IP_ADDRESSES"
+          for IP in "${IPS[@]}"; do
+            echo "Deploying to $IP"
+            ssh -o StrictHostKeyChecking=no -i ssh_key.pem ubuntu@$IP << EOF
+              sudo docker pull $FILTERS_IMAGE_NAME || { echo "Failed to pull image on $IP"; exit 1; }
+              sudo docker stop filters || true
+              sudo docker rm filters || true
+              sudo docker run -d -p 8080:8080 -v /var/run/docker.sock:/var/run/docker.sock --restart=always --name filters --env-file /home/ubuntu/.env $FILTERS_IMAGE_NAME || { echo "Failed to run container on $IP"; exit 1; }
+          EOF
+          done
