commit 28.06.2024 15:20

diff --git a/.github/workflows/polybot-deployment.yaml b/.github/workflows/polybot-deployment.yaml
--- a/.github/workflows/polybot-deployment.yaml
+++ b/.github/workflows/polybot-deployment.yaml
@@ -86,19 +86,27 @@ jobs:
           FILTERS_QUEUE_NAME=https://sqs.eu-west-2.amazonaws.com/019273956931/yaelwil-filters-queue-aws-project.fifo
           ALB_URL=https://yaelwil-alb-aws-project-1971553365.eu-west-2.elb.amazonaws.com:80" > ./polybot/.env
 
-      - name: Copy .env file to EC2 instances
+      - name: Create SSH Key File
         run: |
-          echo ${{ secrets.SSH_PRIVATE_KEY }} > ssh_key.pem
+          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key.pem
           chmod 400 ssh_key.pem
-          cat ssh_key.pem
 
-          IFS=' ' read -r -a IPS <<< "$EC2_POLYBOT_IP_ADDRESSES"
-          for IP in "${IPS[@]}"; do
-            echo "Copying .env file to $IP"
-            scp -o StrictHostKeyChecking=no -i ssh_key.pem ./polybot/.env ubuntu@$IP:/home/ubuntu/polybot/.env || { echo "Failed to copy .env file to EC2 instance $IP"; exit 1; }
-          done
+      - name: Copy .env file to EC2 instances
+        env:
+          ENV_FILE: "./polybot/.env"
+        run: |
+          scp -o StrictHostKeyChecking=no -i ssh_key.pem ./polybot/.env ubuntu@${{ env.EC2_POLYBOT_IP_ADDRESS }}:/home/ubuntu/polybot/.env || { echo "Failed to copy .env file to EC2 instance"; exit 1; }
 
-          rm ssh_key.pem  # Remove the key file after use
+      - name: Copy .env file to EC2 instances
+        env:
+          ENV_FILE: "./polybot/.env"
+        run: |
+          scp -o StrictHostKeyChecking=no -i ssh_key.pem ./polybot/.env ubuntu@${{ EC2_POLYBOT_IP_ADDRESSES }}:/home/ubuntu/polybot/.env || { echo "Failed to copy .env file to EC2 instance"; exit 1; }
+
+      - name: Cleanup SSH Key File
+        run: |
+          rm ssh_key.pem
+
 
       - name: Deploy new version
         run: |
