commit 28.06.2024 15:06

diff --git a/.github/workflows/polybot-deployment.yaml b/.github/workflows/polybot-deployment.yaml
--- a/.github/workflows/polybot-deployment.yaml
+++ b/.github/workflows/polybot-deployment.yaml
@@ -96,7 +96,7 @@ jobs:
           IFS=' ' read -r -a IPS <<< "$EC2_POLYBOT_IP_ADDRESSES"
           for IP in "${IPS[@]}"; do
             echo "Copying .env file to $IP"
-            scp -o StrictHostKeyChecking=no -i ssh_key.pem ./polybot/.env ec2-user@$IP:/home/ec2-user/polybot/.env || { echo "Failed to copy .env file to EC2 instance $IP"; exit 1; }
+            scp -o StrictHostKeyChecking=no -i ssh_key.pem ./polybot/.env ubuntu@$IP:/home/ubuntu/polybot/.env || { echo "Failed to copy .env file to EC2 instance $IP"; exit 1; }
           done
 
           rm ssh_key.pem  # Remove the key file after use
