commit 28.06.2024 15:21

diff --git a/.github/workflows/polybot-deployment.yaml b/.github/workflows/polybot-deployment.yaml
--- a/.github/workflows/polybot-deployment.yaml
+++ b/.github/workflows/polybot-deployment.yaml
@@ -8,24 +8,6 @@ on:
       - main
 
 jobs:
-  Build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: Checkout the repo code
-        uses: actions/checkout@v2
-
-      - name: Build and push image
-        run: |
-          cd polybot
-          
-          # Login to DockerHub         
-          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
-
-          # Build and push Docker image
-          POLYBOT_IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/polybot:0.0.${{ github.run_number }}
-          docker build -t $POLYBOT_IMAGE_NAME .
-          docker push $POLYBOT_IMAGE_NAME
-
   Deploy:
     runs-on: ubuntu-latest
     needs: Build
@@ -55,7 +37,7 @@ jobs:
       - name: Start Stopped Instances
         if: env.EC2_INSTANCE_IDS != ''
         run: |
-          for INSTANCE_ID in $EC2_INSTANCE_IDS; do
+          for INSTANCE_ID in ${{ env.EC2_INSTANCE_IDS }}; do
             echo "Starting instance $INSTANCE_ID"
             aws ec2 start-instances --instance-ids $INSTANCE_ID --region eu-west-2
           done
@@ -63,7 +45,7 @@ jobs:
       - name: Wait for Instances to be Running
         if: env.EC2_INSTANCE_IDS != ''
         run: |
-          for INSTANCE_ID in $EC2_INSTANCE_IDS; do
+          for INSTANCE_ID in ${{ env.EC2_INSTANCE_IDS }}; do
             echo "Waiting for instance $INSTANCE_ID to be running"
             aws ec2 wait instance-running --instance-ids $INSTANCE_ID --region eu-west-2
           done
@@ -71,7 +53,7 @@ jobs:
       - name: Fetch EC2 Instance IP Addresses Again
         if: env.EC2_INSTANCE_IDS != ''
         run: |
-          NEW_RUNNING_INSTANCE_IPS=$(aws ec2 describe-instances --region eu-west-2 --instance-ids $EC2_INSTANCE_IDS --query 'Reservations[*].Instances[*].PublicIpAddress' --output text | grep -v 'None' | tr '\n' ' ')
+          NEW_RUNNING_INSTANCE_IPS=$(aws ec2 describe-instances --region eu-west-2 --instance-ids ${{ env.EC2_INSTANCE_IDS }} --query 'Reservations[*].Instances[*].PublicIpAddress' --output text | grep -v 'None' | tr '\n' ' ')
           echo "NEW_RUNNING_INSTANCE_IPS=$NEW_RUNNING_INSTANCE_IPS" >> $GITHUB_ENV
           EC2_POLYBOT_IP_ADDRESSES="$EC2_POLYBOT_IP_ADDRESSES $NEW_RUNNING_INSTANCE_IPS"
           echo "EC2_POLYBOT_IP_ADDRESSES=$EC2_POLYBOT_IP_ADDRESSES" >> $GITHUB_ENV
@@ -95,18 +77,11 @@ jobs:
         env:
           ENV_FILE: "./polybot/.env"
         run: |
-          scp -o StrictHostKeyChecking=no -i ssh_key.pem ./polybot/.env ubuntu@${{ env.EC2_POLYBOT_IP_ADDRESS }}:/home/ubuntu/polybot/.env || { echo "Failed to copy .env file to EC2 instance"; exit 1; }
-
-      - name: Copy .env file to EC2 instances
-        env:
-          ENV_FILE: "./polybot/.env"
-        run: |
-          scp -o StrictHostKeyChecking=no -i ssh_key.pem ./polybot/.env ubuntu@${{ EC2_POLYBOT_IP_ADDRESSES }}:/home/ubuntu/polybot/.env || { echo "Failed to copy .env file to EC2 instance"; exit 1; }
+          scp -o StrictHostKeyChecking=no -i ssh_key.pem ./polybot/.env ubuntu@${{ env.EC2_POLYBOT_IP_ADDRESSES }}:/home/ubuntu/polybot/.env || { echo "Failed to copy .env file to EC2 instance"; exit 1; }
 
       - name: Cleanup SSH Key File
         run: |
           rm ssh_key.pem
-
 
       - name: Deploy new version
         run: |
@@ -114,11 +89,11 @@ jobs:
           IFS=' ' read -r -a IPS <<< "$EC2_POLYBOT_IP_ADDRESSES"
           for IP in "${IPS[@]}"; do
             echo "Deploying to $IP"
-            ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ec2-user@$IP << EOF || { echo "Failed to SSH into $IP"; exit 1; }
+            ssh -o StrictHostKeyChecking=no -i /path/to/your-key.pem ubuntu@$IP << EOF || { echo "Failed to SSH into $IP"; exit 1; }
               docker pull $POLYBOT_IMAGE_NAME || { echo "Failed to pull image on $IP"; exit 1; }
               sudo docker stop polybot || true
               sudo docker rm polybot || true
-              sudo docker run -d -p 8443:8443 --restart=always --name polybot --env-file /home/ec2-user/polybot/.env $POLYBOT_IMAGE_NAME || { echo "Failed to run container on $IP"; exit 1; }
+              sudo docker run -d -p 8443:8443 --restart=always --name polybot --env-file /home/ubuntu/polybot/.env $POLYBOT_IMAGE_NAME || { echo "Failed to run container on $IP"; exit 1; }
             EOF
           done
 
